version: '3.9'
services:
    kavita:
        image: kizaing/kavita:latest
        volumes:
            - ./manga:/manga
            - ./data/temp:/kavita/temp
            - ./data/cache:/kavita/cache
            - ./data:/kavita/data
            - ./data/logs:/kavita/logs
        ports:
            - "5000:5000"
        restart: unless-stopped
