services:
    kavita:
        image: kizaing/kavita:latest
        container_name: kavita
        volumes:
            - ./manga:/manga            # Manga is just an example you can have the name you want. See the following
            - ./comics:/comics          # Optional
            - ./books:/books            # Optional
            - ./config:/kavita/config   # Change './config if you want to have the config files in a different place.
                                        # /kavita/config must not be changed
        environment:
            - TZ=Your/Timezone
        ports:
            - "5000:5000"
        restart: unless-stopped
        
        #Uncomment if you want to implement healthchecks
        #healthcheck:
        #   test: curl --fail http://localhost:5000 || exit 1
        #   interval: 300s
        #   retries: 3
        #   start_period: 30s
        #   timeout: 15s
