name: Bug Report
description: Create a report to help us improve
title: "Bug Title Here"  # Add a title field
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: markdown
    attributes:
      value: "If you have a feature request, please submit on [Github Discussions](https://github.com/Kareadita/Kavita/discussions/2529)."
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what steps you took so we can try to reproduce.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: What did you expect?
      description: What did you expect to happen?
      placeholder: Tell us what you expected to see!
      value: ""
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version are you running?
      placeholder: Can be found by going to Server Settings > System
      value: ""
    validations:
      required: true
  - type: dropdown
    id: OS
    attributes:
      label: What OS is Kavita being run on?
      multiple: false
      options:
        - Docker
        - Windows
        - Linux
        - Mac
  - type: dropdown
    id: desktop-OS
    attributes:
      label: If the issue is being seen on Desktop, what OS are you running where you see the issue?
      multiple: false
      options:
        - Windows
        - Linux
        - Mac
  - type: dropdown
    id: desktop-browsers
    attributes:
      label: If the issue is being seen in the UI, what browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: mobile-OS
    attributes:
      label: If the issue is being seen on Mobile, what OS are you running where you see the issue?
      multiple: false
      options:
        - Android
        - iOS
  - type: dropdown
    id: mobile-browsers
    attributes:
      label: If the issue is being seen on the UI, what browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: anything-else
    attributes:
      label: Additional Notes
      description: Any other information about the issue not covered in this form?
      placeholder: e.g. Running Kavita on a Raspberry Pi, updating from X version, using LSIO container, etc
    validations:
      required: true
