using Kavita.Models.Entities.Enums;
using Kavita.Services.Scanner;

namespace Kavita.Services.Tests.Parsing;

public class MangaParsingTests
{
    [Theory]
    [InlineData("Killing Bites Vol. 0001 Ch. 0001 - Galactica Scanlations (gb)", "1")]
    [InlineData("My Girlfriend Is Shobitch v01 - ch. 09 - pg. 008.png", "1")]
    [InlineData("Historys Strongest Disciple Kenichi_v11_c90-98.zip", "11")]
    [InlineData("B_Gata_H_Kei_v01[SlowManga&OverloadScans]", "1")]
    [InlineData("BTOOOM! v01 (2013) (Digital) (Shadowcat-Empire)", "1")]
    [InlineData("Gokukoku no Brynhildr - c001-008 (v01) [TrinityBAKumA]", "1")]
    [InlineData("Dance in the Vampire Bund v16-17 (Digital) (NiceDragon)", "16-17")]
    [InlineData("Akame ga KILL! ZERO v01 (2016) (Digital) (LuCaZ).cbz", "1")]
    [InlineData("v001", "1")]
    [InlineData("Vol 1", "1")]
    [InlineData("vol_356-1", "356")] // Mangapy syntax
    [InlineData("No Volume", Parser.LooseLeafVolume)]
    [InlineData("U12 (Under 12) Vol. 0001 Ch. 0001 - Reiwa Scans (gb)", "1")]
    [InlineData("[Suihei Kiki]_Kasumi_Otoko_no_Ko_[Taruby]_v1.1.zip", "1.1")]
    [InlineData("Tonikaku Cawaii [Volume 11].cbz", "11")]
    [InlineData("[WS]_Ichiban_Ushiro_no_Daimaou_v02_ch10.zip", "2")]
    [InlineData("[xPearse] Kyochuu Rettou Volume 1 [English] [Manga] [Volume Scans]", "1")]
    [InlineData("Tower Of God S01 014 (CBT) (digital).cbz", "1")]
    [InlineData("Tenjou_Tenge_v17_c100[MT].zip", "17")]
    [InlineData("Shimoneta - Manmaru Hen - c001-006 (v01) [Various].zip", "1")]
    [InlineData("Future Diary v02 (2009) (Digital) (Viz).cbz", "2")]
    [InlineData("Mujaki no Rakuen Vol12 ch76", "12")]
    [InlineData("Ichinensei_ni_Nacchattara_v02_ch11_[Taruby]_v1.3.zip", "2")]
    [InlineData("Dorohedoro v01 (2010) (Digital) (LostNerevarine-Empire).cbz", "1")]
    [InlineData("Dorohedoro v11 (2013) (Digital) (LostNerevarine-Empire).cbz", "11")]
    [InlineData("Yumekui_Merry_v01_c01[Bakayarou-Kuu].rar", "1")]
    [InlineData("Yumekui-Merry_DKThias_Chapter11v2.zip", Parser.LooseLeafVolume)]
    [InlineData("Itoshi no Karin - c001-006x1 (v01) [Renzokusei Scans]", "1")]
    [InlineData("Kedouin Makoto - Corpse Party Musume, Chapter 12", Parser.LooseLeafVolume)]
    [InlineData("VanDread-v01-c001[MD].zip", "1")]
    [InlineData("Ichiban_Ushiro_no_Daimaou_v04_ch27_[VISCANS].zip", "4")]
    [InlineData("Mob Psycho 100 v02 (2019) (Digital) (Shizu).cbz", "2")]
    [InlineData("Kodomo no Jikan vol. 1.cbz", "1")]
    [InlineData("Kodomo no Jikan vol. 10.cbz", "10")]
    [InlineData("Kedouin Makoto - Corpse Party Musume, Chapter 12 [Dametrans][v2]", Parser.LooseLeafVolume)]
    [InlineData("Vagabond_v03", "3")]
    [InlineData("Mujaki No Rakune Volume 10.cbz", "10")]
    [InlineData("Umineko no Naku Koro ni - Episode 3 - Banquet of the Golden Witch #02.cbz", Parser.LooseLeafVolume)]
    [InlineData("Volume 12 - Janken Boy is Coming!.cbz", "12")]
    [InlineData("[dmntsf.net] One Piece - Digital Colored Comics Vol. 20 Ch. 177 - 30 Million vs 81 Million.cbz", "20")]
    [InlineData("Gantz.V26.cbz", "26")]
    [InlineData("NEEDLESS_Vol.4_-Simeon_6_v2[SugoiSugoi].rar", "4")]
    [InlineData("[Hidoi]_Amaenaideyo_MS_vol01_chp02.rar", "1")]
    [InlineData("NEEDLESS_Vol.4_-_Simeon_6_v2_[SugoiSugoi].rar", "4")]
    [InlineData("Okusama wa Shougakusei c003 (v01) [bokuwaNEET]", "1")]
    [InlineData("Sword Art Online Vol 10 - Alicization Running [Yen Press] [LuCaZ] {r2}.epub", "10")]
    [InlineData("Noblesse - Episode 406 (52 Pages).7z", Parser.LooseLeafVolume)]
    [InlineData("X-Men v1 #201 (September 2007).cbz", "1")]
    [InlineData("Hentai Ouji to Warawanai Neko. - Vol. 06 Ch. 034.5", "6")]
    [InlineData("The 100 Girlfriends Who Really, Really, Really, Really, Really Love You - Vol. 03 Ch. 023.5 - Volume 3 Extras.cbz", "3")]
    [InlineData("The 100 Girlfriends Who Really, Really, Really, Really, Really Love You - Vol. 03.5 Ch. 023.5 - Volume 3 Extras.cbz", "3.5")]
    [InlineData("幽游白书完全版 第03卷 天下", "3")]
    [InlineData("阿衰online 第1册", "1")]
    [InlineData("【TFO汉化&Petit汉化】迷你偶像漫画卷2第25话", "2")]
    [InlineData("スライム倒して300年、知らないうちにレベルMAXになってました 1巻", "1")]
    [InlineData("スライム倒して300年、知らないうちにレベルMAXになってました 1-3巻", "1-3")]
    [InlineData("Dance in the Vampire Bund {Special Edition} v03.5 (2019) (Digital) (KG Manga)", "3.5")]
    [InlineData("Kebab Том 1 Глава 3", "1")]
    [InlineData("Манга Глава 2", Parser.LooseLeafVolume)]
    [InlineData("Манга Тома 1-4", "1-4")]
    [InlineData("Манга Том 1-4", "1-4")]
    [InlineData("동의보감 13장", "13")]
    [InlineData("몰?루 아카이브 7.5권", "7.5")]
    [InlineData("63권#200", "63")]
    [InlineData("시즌34삽화2", "34")]
    [InlineData("시즌3-4삽화2", "3-4")]
    [InlineData("Accel World Chapter 001 Volume 002", "2")]
    [InlineData("Accel World Volume 2", "2")]
    [InlineData("Nagasarete Airantou - Vol. 30 Ch. 187.5 - Vol.31 Omake", "30")]
    [InlineData("Zom 100 - Bucket List of the Dead v01",  "1")]
    // Tome Tests
    [InlineData("Daredevil - t6 - 10 - (2019)", "6")]
    [InlineData("Batgirl T2000 #57", "2000")]
    [InlineData("Teen Titans t1 001 (1966-02) (digital) (OkC.O.M.P.U.T.O.-Novus)", "1")]
    [InlineData("Conquistador_Tome_2", "2")]
    [InlineData("Max_l_explorateur-_Tome_0", "0")]
    [InlineData("Chevaliers d'Héliopolis T3 - Rubedo, l'oeuvre au rouge (Jodorowsky & Jérémy)", "3")]
    [InlineData("Adventure Time (2012)/Adventure Time  Ch 1 (2012)", Parser.LooseLeafVolume)]
    [InlineData("Adventure Time TPB (2012)/Adventure Time v01 (2012).cbz", "1")]
    [InlineData("Monster Ch. 001 [MangaPlus] [Digital] [amit34521]", Parser.LooseLeafVolume)]
    [InlineData("Alter Ego (2020) (Digital) (v3dio)", Parser.LooseLeafVolume)]
    [InlineData("Alter Ego (2020) (Digital) (t3dio)", Parser.LooseLeafVolume)]
    [InlineData("The Space Pirate COBRA v11 - Magic Doll Vol.1 [MDKM] (Creek & River)", "11")]
    [InlineData("Pokémon Adventures v04 - Yellow v01 (AnHeroGold-Empire)", "4")]
    [InlineData("조선왕조실톡 106권", "106")]
    // Bare year before an explicit Volume/Tome marker should not be swallowed into the volume number
    [InlineData("Blade Runner 2019 - Volume 1.pdf", "1")]
    [InlineData("Cyberpunk 2077 - Volume 2.cbz", "2")]
    [InlineData("Blade Runner 2019 - Tome 1.cbz", "1")]
    // A bare year before an explicit Chapter marker (no volume marker present) should not leak into the volume either
    [InlineData("Blade Runner 2019 - Ch. 1.pdf", Parser.LooseLeafVolume)]
    [InlineData("Blade Runner 2019 - Chapter 1.pdf", Parser.LooseLeafVolume)]
    // GH #1534: these are volume-only releases - the number embedded in the series title must not
    // interfere with reading the actual "vNN" volume marker.
    [InlineData("ACCA - 13-Territory Inspection Department v01 (2017) (Digital) (Uasaha).cbz", "1")]
    [InlineData("ACCA - 13-Territory Inspection Department P.S. v01 (2020) (Digital) (LuCaZ).cbz", "1")]
    [InlineData("Brave 10 v01 (2013) (Digital) (Lovag-Empire).cbz", "1")]
    [InlineData("Black Panther and Sweet 16 v01 (2017) (Digital) (danke-Empire).cbz", "1")]
    [InlineData("Boys Over Flowers Season 2 v01 (2017) (Digital) (ripper).cbz", "1")]
    [InlineData("Chillin' in Another World with Level 2 Super Cheat Powers v01 (2021) (Digital) (danke-Empire + nao).cbz", "1")]
    [InlineData("Cyborg 009 v01 (2003) (Digital) (BlurPixel-Empire).cbr", "1")]
    [InlineData("Dementia 21 v01 (2018) (digital) (tunafan).cbr", "1")]
    [InlineData("Golgo 13 v01 - Supergun (2006) (Digital) (danke-Empire).cbz", "1")]
    [InlineData("GTO - 14 Days in Shonan v01 (2022) (Digital) (danke-Empire).cbz", "1")]
    [InlineData("Level 1 Demon Lord & One Room Hero v01 (2021) (Digital) (danke-Empire).cbz", "1")]
    [InlineData("My Unique Skill Makes Me OP Even at Level 1 v01 (2021) (Digital) (danke-Empire) (F).cbz", "1")]
    [InlineData("Otherworldly Munchkin - Let's Speedrun the Dungeon with Only 1 HP! v01 (2020) (Digital) (danke-Empire) (F).cbz", "1")]
    [InlineData("Rosario+Vampire Season 2 v01 (2010) (Digital) (LostNerevarine-Empire).cbz", "1")]
    [InlineData("Samurai 8 v01 (2020) (Digital) (danke-Empire).cbz", "1")]
    [InlineData("Samurai 8 - The Tale of Hachimaru v01 (2020) (Digital) (danke-Empire).cbz", "1")]
    [InlineData("Saving 80,000 Gold in Another World for my Retirement v01 (2019) (Digital) (danke-Empire).cbz", "1")]
    [InlineData("Sekirei v19 - 365 Days Without Her (2018) (Digital) (RedRain).cbz", "19")]
    [InlineData("Sex Ed 120% v01 (2021) (Digital) (danke-Empire).cbz", "1")]
    [InlineData("Higurashi When They Cry - Arc 1 - Abducted by Demons Arc v01 (2008) (Digital) (LuCaZ).cbz", "1")]
    [InlineData("Umineko When They Cry - Episode 1 - Legend of the Golden Witch v01 (2-in-1 Edition) (2012) (Digital SD) (Ushi) (Spreads Joined).cbz", "1")]
    [InlineData("Umineko When They Cry - Episode 8 - Twilight of the Golden Witch v01 (3-in-1 Edition) (2019) (Digital SD) (Ushi) (Spreads Joined).cbz", "1")]
    [InlineData("JoJo's Bizarre Adventure - Part 1 - Phantom Blood v01 (2014) (Digital) (BlackManta-Empire).cbz", "1")]
    [InlineData("JoJo's Bizarre Adventure - Part 5 - Golden Wind v01 (2021) (Digital) (1r0n) (f2).cbz", "1")]
    [InlineData("Ascendance of a Bookworm - Part 01 v01 (2021) (Digital) (Ushi).cbz", "1")]
    [InlineData("Ascendance of a Bookworm - Part 02 v01 (2021) (Digital) (Ushi).cbz", "1")]
    [InlineData("Rose Guns Days - Season 1 v01 (2015) (Digital) (LuCaZ).cbz", "1")]
    [InlineData("Rose Guns Days - Season 2 v01 (2016) (Digital) (LuCaZ).cbz", "1")]
    [InlineData("Showa - A History of Japan v01 - 1926-1939 (2013) (Digital) (XRA-Empire).cbz", "1")]
    [InlineData("Showa - A History of Japan v02 - 1939-1944 (2014) (Digital) (XRA-Empire).cbz", "2")]
    [InlineData("Showa - A History of Japan v03 - 1944-1953 (2014) (Digital) (XRA-Empire).cbz", "3")]
    [InlineData("Showa - A History of Japan v04 - 1953-1989 (2015) (Digital) (XRA-Empire).cbz", "4")]
    [InlineData("Path of the Assassin v09 - Battle for Power Part 1 (2008) (Digital) (Lovag-Empire).cbz", "9")]
    [InlineData("Path of the Assassin v10 - Battle for Power Part 2 (2008) (Digital) (Lovag-Empire).cbz", "10")]
    [InlineData("Kaiju No. 8 v01 (2021) (Digital) (1r0n) (f).cbz", "1")]
    [InlineData("No. 5 v01 (2021) (Digital) (1r0n) (f2).cbz", "1")]
    [InlineData("No. 6 v1 (2015) (Digital) (ripper).cbz", "1")]

    // GH #1534: ripper tag "c1fi7" must not interfere with reading the volume either
    [InlineData("No. 6 v1 (2015) (Digital) (c1fi7).cbz", "1")]
    [InlineData("Some Manga v01 (2015) (Digital) (Mr. Kimiko-c1fi7).cbz", "1")]
    public void ParseVolumeTest(string filename, string expected)
    {
        Assert.Equal(expected, Parser.ParseVolume(filename, LibraryType.Manga));
    }

    [Theory]
    [InlineData("One Piece - Vol 2 Ch 1.1 - Volume 4 Omakes", "2")]
    [InlineData("Attack on Titan - Vol. 5 Ch. 20 - Vol.10 Special", "5")]
    [InlineData("Naruto - Volume 1 Chapter 1 - Volume 2 Preview", "1")]
    [InlineData("My Hero Academia - Vol 15 - Vol 20 Extras", "15")]

    // Edge cases for duplicate detection
    [InlineData("Series - Vol 1 - Not Vol but Voldemort", "1")] // Should not trigger false positive
    [InlineData("Volume Wars - Vol 1 vs Vol 2", "1")] // Series name contains "Volume"
    [InlineData("Vol 3 - The Volume Chronicles - Vol 5", "3")] // Multiple volume references

    // Thai Volume tests
    [InlineData("เล่ม 5 - Chapter 1", "5")]
    [InlineData("เล่มที่ 12 Test", "12")]

    // Chinese Volume tests
    [InlineData("幽游白书完全版 第03卷 天下", "3")]
    [InlineData("阿衰online 第1册", "1")]
    [InlineData("卷5 Test", "5")]
    [InlineData("册10 Test", "10")]

    // Korean Volume tests
    [InlineData("제5권 Test", "5")]
    [InlineData("10화 Test", Parser.LooseLeafVolume)]
    [InlineData("10장 Test", "10")]
    [InlineData("시즌3 Test", "3")]
    [InlineData("5시즌 Test", Parser.LooseLeafVolume)]

    // Japanese Volume tests
    [InlineData("Test 5巻", "5")]
    [InlineData("Series 10-15巻", "10-15")]

    // Russian Volume tests
    [InlineData("Том 5 Test", "5")]
    [InlineData("Тома 10 Test", "10")]
    [InlineData("5 Том Test", "5")]
    public void ParseDuplicateVolumeTest(string filename, string expected)
    {
        Assert.Equal(expected, Parser.ParseVolume(filename, LibraryType.Manga));
    }

    [Theory]
    [InlineData("Killing Bites Vol. 0001 Ch. 0001 - Galactica Scanlations (gb)", "Killing Bites")]
    [InlineData("My Girlfriend Is Shobitch v01 - ch. 09 - pg. 008.png", "My Girlfriend Is Shobitch")]
    [InlineData("Historys Strongest Disciple Kenichi_v11_c90-98.zip", "Historys Strongest Disciple Kenichi")]
    [InlineData("B_Gata_H_Kei_v01[SlowManga&OverloadScans]", "B Gata H Kei")]
    [InlineData("BTOOOM! v01 (2013) (Digital) (Shadowcat-Empire)", "BTOOOM!")]
    [InlineData("Gokukoku no Brynhildr - c001-008 (v01) [TrinityBAKumA]", "Gokukoku no Brynhildr")]
    [InlineData("Dance in the Vampire Bund v16-17 (Digital) (NiceDragon)", "Dance in the Vampire Bund")]
    [InlineData("v001", "")]
    [InlineData("U12 (Under 12) Vol. 0001 Ch. 0001 - Reiwa Scans (gb)", "U12")]
    [InlineData("Akame ga KILL! ZERO (2016-2019) (Digital) (LuCaZ)", "Akame ga KILL! ZERO")]
    [InlineData("APOSIMZ 017 (2018) (Digital) (danke-Empire).cbz", "APOSIMZ")]
    [InlineData("Akiiro Bousou Biyori - 01.jpg", "Akiiro Bousou Biyori")]
    [InlineData("Beelzebub_172_RHS.zip", "Beelzebub")]
    [InlineData("Dr. STONE 136 (2020) (Digital) (LuCaZ).cbz", "Dr. STONE")]
    [InlineData("Cynthia the Mission 29.rar", "Cynthia the Mission")]
    [InlineData("Darling in the FranXX - Volume 01.cbz", "Darling in the FranXX")]
    [InlineData("Darwin's Game - Volume 14 (F).cbz", "Darwin's Game")]
    [InlineData("[BAA]_Darker_than_Black_c7.zip", "Darker than Black")]
    [InlineData("Kedouin Makoto - Corpse Party Musume, Chapter 19 [Dametrans].zip", "Kedouin Makoto - Corpse Party Musume")]
    [InlineData("Kedouin Makoto - Corpse Party Musume, Chapter 01", "Kedouin Makoto - Corpse Party Musume")]
    [InlineData("[WS]_Ichiban_Ushiro_no_Daimaou_v02_ch10.zip", "Ichiban Ushiro no Daimaou")]
    [InlineData("[xPearse] Kyochuu Rettou Volume 1 [English] [Manga] [Volume Scans]", "Kyochuu Rettou")]
    [InlineData("Loose_Relation_Between_Wizard_and_Apprentice_c07[AN].zip", "Loose Relation Between Wizard and Apprentice")]
    [InlineData("Tower Of God S01 014 (CBT) (digital).cbz", "Tower Of God")]
    [InlineData("Tenjou_Tenge_c106[MT].zip", "Tenjou Tenge")]
    [InlineData("Tenjou_Tenge_v17_c100[MT].zip", "Tenjou Tenge")]
    [InlineData("Shimoneta - Manmaru Hen - c001-006 (v01) [Various].zip", "Shimoneta - Manmaru Hen")]
    [InlineData("Future Diary v02 (2009) (Digital) (Viz).cbz", "Future Diary")]
    [InlineData("Tonikaku Cawaii [Volume 11].cbz", "Tonikaku Cawaii")]
    [InlineData("Mujaki no Rakuen Vol12 ch76", "Mujaki no Rakuen")]
    [InlineData("Knights of Sidonia c000 (S2 LE BD Omake - BLAME!) [Habanero Scans]", "Knights of Sidonia")]
    [InlineData("Vol 1.cbz", "")]
    [InlineData("Ichinensei_ni_Nacchattara_v01_ch01_[Taruby]_v1.1.zip", "Ichinensei ni Nacchattara")]
    [InlineData("Chrno_Crusade_Dragon_Age_All_Stars[AS].zip", "")]
    [InlineData("Ichiban_Ushiro_no_Daimaou_v04_ch34_[VISCANS].zip", "Ichiban Ushiro no Daimaou")]
    [InlineData("Rent a Girlfriend v01.cbr", "Rent a Girlfriend")]
    [InlineData("Yumekui_Merry_v01_c01[Bakayarou-Kuu].rar", "Yumekui Merry")]
    [InlineData("Itoshi no Karin - c001-006x1 (v01) [Renzokusei Scans]", "Itoshi no Karin")]
    [InlineData("Tonikaku Kawaii Vol-1 (Ch 01-08)", "Tonikaku Kawaii")]
    [InlineData("Tonikaku Kawaii (Ch 59-67) (Ongoing)", "Tonikaku Kawaii")]
    [InlineData("7thGARDEN v01 (2016) (Digital) (danke).cbz", "7thGARDEN")]
    [InlineData("Kedouin Makoto - Corpse Party Musume, Chapter 12", "Kedouin Makoto - Corpse Party Musume")]
    [InlineData("Kedouin Makoto - Corpse Party Musume, Chapter 09", "Kedouin Makoto - Corpse Party Musume")]
    [InlineData("Goblin Slayer Side Story - Year One 025.5", "Goblin Slayer Side Story - Year One")]
    [InlineData("Goblin Slayer - Brand New Day 006.5 (2019) (Digital) (danke-Empire)", "Goblin Slayer - Brand New Day")]
    [InlineData("Kedouin Makoto - Corpse Party Musume, Chapter 01 [Dametrans][v2]", "Kedouin Makoto - Corpse Party Musume")]
    [InlineData("Vagabond_v03", "Vagabond")]
    [InlineData("[AN] Mahoutsukai to Deshi no Futekisetsu na Kankei Chp. 1", "Mahoutsukai to Deshi no Futekisetsu na Kankei")]
    [InlineData("Beelzebub_Side_Story_02_RHS.zip", "Beelzebub Side Story")]
    [InlineData("Baketeriya ch01-05.zip", "Baketeriya")]
    [InlineData("[PROzess]Kimi_ha_midara_na_Boku_no_Joou_-_Ch01", "Kimi ha midara na Boku no Joou")]
    [InlineData("[SugoiSugoi]_NEEDLESS_Vol.2_-_Disk_The_Informant_5_[ENG].rar", "NEEDLESS")]
    [InlineData("Fullmetal Alchemist chapters 101-108.cbz", "Fullmetal Alchemist")]
    [InlineData("To Love Ru v09 Uncensored (Ch.071-079).cbz", "To Love Ru")]
    [InlineData("[dmntsf.net] One Piece - Digital Colored Comics Vol. 20 Ch. 177 - 30 Million vs 81 Million.cbz", "One Piece - Digital Colored Comics")]
    [InlineData("Corpse Party -The Anthology- Sachikos game of love Hysteric Birthday 2U Chapter 01", "Corpse Party -The Anthology- Sachikos game of love Hysteric Birthday 2U")]
    [InlineData("Vol03_ch15-22.rar", "")]
    [InlineData("Love Hina - Special.cbz", "")] // This has to be a fallback case
    [InlineData("Ani-Hina Art Collection.cbz", "")] // This has to be a fallback case
    [InlineData("Magi - Ch.252-005.cbz", "Magi")]
    [InlineData("Umineko no Naku Koro ni - Episode 1 - Legend of the Golden Witch #1", "Umineko no Naku Koro ni")]
    [InlineData("Kimetsu no Yaiba - Digital Colored Comics c162 Three Victorious Stars.cbz", "Kimetsu no Yaiba - Digital Colored Comics")]
    [InlineData("[Hidoi]_Amaenaideyo_MS_vol01_chp02.rar", "Amaenaideyo MS")]
    [InlineData("NEEDLESS_Vol.4_-_Simeon_6_v2_[SugoiSugoi].rar", "NEEDLESS")]
    [InlineData("Okusama wa Shougakusei c003 (v01) [bokuwaNEET]", "Okusama wa Shougakusei")]
    [InlineData("VanDread-v01-c001[MD].zip", "VanDread")]
    [InlineData("Momo The Blood Taker - Chapter 027 Violent Emotion.cbz", "Momo The Blood Taker")]
    [InlineData("Kiss x Sis - Ch.15 - The Angst of a 15 Year Old Boy.cbz", "Kiss x Sis")]
    [InlineData("Green Worldz - Chapter 112 Final Chapter (End).cbz", "Green Worldz")]
    [InlineData("Noblesse - Episode 406 (52 Pages).7z", "Noblesse")]
    [InlineData("X-Men v1 #201 (September 2007).cbz", "X-Men")]
    [InlineData("Kodoja #001 (March 2016)", "Kodoja")]
    [InlineData("Boku No Kokoro No Yabai Yatsu - Chapter 054 I Prayed At The Shrine (V0).cbz", "Boku No Kokoro No Yabai Yatsu")]
    [InlineData("Kiss x Sis - Ch.36 - A Cold Home Visit.cbz", "Kiss x Sis")]
    [InlineData("Seraph of the End - Vampire Reign 093 (2020) (Digital) (LuCaZ)", "Seraph of the End - Vampire Reign")]
    [InlineData("Grand Blue Dreaming - SP02 Extra (2019) (Digital) (danke-Empire).cbz", "Grand Blue Dreaming")]
    [InlineData("Yuusha Ga Shinda! - Vol.tbd Chapter 27.001 V2 Infection ①.cbz", "Yuusha Ga Shinda!")]
    [InlineData("Seraph of the End - Vampire Reign 093 (2020) (Digital) (LuCaZ).cbz", "Seraph of the End - Vampire Reign")]
    [InlineData("Getsuyoubi no Tawawa - Ch. 001 - Ai-chan, Part 1", "Getsuyoubi no Tawawa")]
    [InlineData("Please Go Home, Akutsu-San! - Chapter 038.5 - Volume Announcement.cbz", "Please Go Home, Akutsu-San!")]
    [InlineData("Killing Bites - Vol 11 Chapter 050 Save Me, Nunupi!.cbz", "Killing Bites")]
    [InlineData("Mad Chimera World - Volume 005 - Chapter 026.cbz", "Mad Chimera World")]
    [InlineData("Hentai Ouji to Warawanai Neko. - Vol. 06 Ch. 034.5", "Hentai Ouji to Warawanai Neko.")]
    [InlineData("The 100 Girlfriends Who Really, Really, Really, Really, Really Love You - Vol. 03 Ch. 023.5 - Volume 3 Extras.cbz", "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You")]
    [InlineData("Kimi no Koto ga Daidaidaidaidaisuki na 100-nin no Kanojo Chapter 1-10", "Kimi no Koto ga Daidaidaidaidaisuki na 100-nin no Kanojo")]
    [InlineData("The Duke of Death and His Black Maid - Ch. 177 - The Ball (3).cbz", "The Duke of Death and His Black Maid")]
    [InlineData("The Duke of Death and His Black Maid - Vol. 04 Ch. 054.5 - V4 Omake", "The Duke of Death and His Black Maid")]
    [InlineData("Vol. 04 Ch. 054.5", "")]
    [InlineData("Great_Teacher_Onizuka_v16[TheSpectrum]", "Great Teacher Onizuka")]
    [InlineData("[Renzokusei]_Kimi_wa_Midara_na_Boku_no_Joou_Ch5_Final_Chapter", "Kimi wa Midara na Boku no Joou")]
    [InlineData("Battle Royale, v01 (2000) [TokyoPop] [Manga-Sketchbook]", "Battle Royale")]
    [InlineData("Kaiju No. 8 036 (2021) (Digital)", "Kaiju No. 8")]
    [InlineData("Seraph of the End - Vampire Reign 093  (2020) (Digital) (LuCaZ).cbz", "Seraph of the End - Vampire Reign")]
    [InlineData("Love Hina - Volume 01 [Scans].pdf", "Love Hina")]
    [InlineData("It's Witching Time! 001 (Digital) (Anonymous1234)", "It's Witching Time!")]
    [InlineData("Zettai Karen Children v02 c003 - The Invisible Guardian (2) [JS Scans]", "Zettai Karen Children")]
    [InlineData("My Charms Are Wasted on Kuroiwa Medaka - Ch. 37.5 - Volume Extras", "My Charms Are Wasted on Kuroiwa Medaka")]
    [InlineData("Highschool of the Dead - Full Color Edition v02 [Uasaha] (Yen Press)", "Highschool of the Dead - Full Color Edition")]
    [InlineData("諌山創] 進撃の巨人 第23巻", "諌山創] 進撃の巨人")]
    [InlineData("(一般コミック) [奥浩哉] いぬやしき 第09巻", "いぬやしき")]
    [InlineData("Highschool of the Dead - 02", "Highschool of the Dead")]
    [InlineData("Kebab Том 1 Глава 3", "Kebab")]
    [InlineData("Манга Глава 2", "Манга")]
    [InlineData("Манга Глава 2-2", "Манга")]
    [InlineData("Манга Том 1 3-4 Глава", "Манга")]
    [InlineData("Esquire 6권 2021년 10월호", "Esquire")]
    [InlineData("Accel World: Vol 1", "Accel World")]
    [InlineData("Accel World Chapter 001 Volume 002", "Accel World")]
    [InlineData("Bleach 001-003", "Bleach")]
    [InlineData("Accel World Volume 2", "Accel World")]
    [InlineData("죠시라쿠! 2년 후 v01", "죠시라쿠! 2년 후")]
    [InlineData("죠시라쿠! 2년 후 1권", "죠시라쿠! 2년 후")]
    [InlineData("test 2 years 1권", "test 2 years")]
    [InlineData("test 2 years 1화", "test 2 years")]
    [InlineData("Nagasarete Airantou - Vol. 30 Ch. 187.5 - Vol.30 Omake", "Nagasarete Airantou")]
    [InlineData("Cynthia The Mission - c000 - c006 (v06)", "Cynthia The Mission")]
    [InlineData("เด็กคนนี้ขอลาออกจากการเป็นเจ้าของปราสาท เล่ม 1", "เด็กคนนี้ขอลาออกจากการเป็นเจ้าของปราสาท")]
    [InlineData("Max Level Returner เล่มที่ 5", "Max Level Returner")]
    [InlineData("หนึ่งความคิด นิจนิรันดร์ เล่ม 2", "หนึ่งความคิด นิจนิรันดร์")]
    [InlineData("不安の種\uff0b - 01", "不安の種\uff0b")]
    [InlineData("Giant Ojou-sama - Ch. 33.5 - Volume 04 Bonus Chapter", "Giant Ojou-sama")]
    [InlineData("[218565]-(C92) [BRIO (Puyocha)] Mika-nee no Tanryoku Shidou - Mika s Guide to Self-Confidence (THE IDOLM@STE", "")]
    [InlineData("Monster #8 Ch. 001", "Monster #8")]
    [InlineData("Zom 100 - Bucket List of the Dead v01",  "Zom 100 - Bucket List of the Dead")]
    [InlineData("Zom 100 - Tome 2", "Zom 100")]
    [InlineData("Max_l_explorateur Tome 0", "Max l explorateur")]
    [InlineData("Chevaliers d'Héliopolis T3 - Rubedo, l'oeuvre au rouge (Jodorowsky & Jérémy)", "Chevaliers d'Héliopolis")]
    [InlineData("Bd Fr-Aldebaran-Antares-t6", "Bd Fr-Aldebaran-Antares")]
    [InlineData("Monster Ch. 001 [MangaPlus] [Digital] [amit34521]", "Monster")]
    [InlineData("Rent-a-(Really Shy)-Girlfriend Vol 01", "Rent-a-(Really Shy)-Girlfriend")]
    [InlineData("Rent-a-(Really Shy)-Girlfriend (Digital) Vol 01", "Rent-a-(Really Shy)-Girlfriend")]
    [InlineData("Rent-a-Girlfriend v01 (Digital)", "Rent-a-Girlfriend")]
    [InlineData("Fate-(stay night)-Heaven's Feel Vol 01", "Fate-(stay night)-Heaven's Feel")]
    [InlineData("Some Series (2019) (Digital) (LuCaZ) v01", "Some Series")]
    // GH #1534: a number embedded in the series title (before the volume marker) must stay part
    // of the series name rather than being sliced off as if it were a chapter/volume boundary.
    [InlineData("ACCA - 13-Territory Inspection Department v01 (2017) (Digital) (Uasaha).cbz", "ACCA - 13-Territory Inspection Department")]
    [InlineData("ACCA - 13-Territory Inspection Department P.S. v01 (2020) (Digital) (LuCaZ).cbz", "ACCA - 13-Territory Inspection Department P.S.")]
    [InlineData("Brave 10 v01 (2013) (Digital) (Lovag-Empire).cbz", "Brave 10")]
    [InlineData("Black Panther and Sweet 16 v01 (2017) (Digital) (danke-Empire).cbz", "Black Panther and Sweet 16")]
    [InlineData("Boys Over Flowers Season 2 v01 (2017) (Digital) (ripper).cbz", "Boys Over Flowers Season 2")]
    [InlineData("Chillin' in Another World with Level 2 Super Cheat Powers v01 (2021) (Digital) (danke-Empire + nao).cbz", "Chillin' in Another World with Level 2 Super Cheat Powers")]
    [InlineData("Cyborg 009 v01 (2003) (Digital) (BlurPixel-Empire).cbr", "Cyborg 009")]
    [InlineData("Dementia 21 v01 (2018) (digital) (tunafan).cbr", "Dementia 21")]
    [InlineData("Golgo 13 v01 - Supergun (2006) (Digital) (danke-Empire).cbz", "Golgo 13")]
    [InlineData("GTO - 14 Days in Shonan v01 (2022) (Digital) (danke-Empire).cbz", "GTO - 14 Days in Shonan")]
    [InlineData("Level 1 Demon Lord & One Room Hero v01 (2021) (Digital) (danke-Empire).cbz", "Level 1 Demon Lord & One Room Hero")]
    [InlineData("My Unique Skill Makes Me OP Even at Level 1 v01 (2021) (Digital) (danke-Empire) (F).cbz", "My Unique Skill Makes Me OP Even at Level 1")]
    [InlineData("Otherworldly Munchkin - Let's Speedrun the Dungeon with Only 1 HP! v01 (2020) (Digital) (danke-Empire) (F).cbz", "Otherworldly Munchkin - Let's Speedrun the Dungeon with Only 1 HP!")]
    [InlineData("Rosario+Vampire Season 2 v01 (2010) (Digital) (LostNerevarine-Empire).cbz", "Rosario+Vampire Season 2")]
    [InlineData("Samurai 8 v01 (2020) (Digital) (danke-Empire).cbz", "Samurai 8")]
    [InlineData("Samurai 8 - The Tale of Hachimaru v01 (2020) (Digital) (danke-Empire).cbz", "Samurai 8 - The Tale of Hachimaru")]
    [InlineData("Saving 80,000 Gold in Another World for my Retirement v01 (2019) (Digital) (danke-Empire).cbz", "Saving 80,000 Gold in Another World for my Retirement")]
    [InlineData("Sekirei v19 - 365 Days Without Her (2018) (Digital) (RedRain).cbz", "Sekirei")]
    [InlineData("Sex Ed 120% v01 (2021) (Digital) (danke-Empire).cbz", "Sex Ed 120%")]
    [InlineData("Higurashi When They Cry - Arc 1 - Abducted by Demons Arc v01 (2008) (Digital) (LuCaZ).cbz", "Higurashi When They Cry - Arc 1 - Abducted by Demons Arc")]
    [InlineData("Umineko When They Cry - Episode 1 - Legend of the Golden Witch v01 (2-in-1 Edition) (2012) (Digital SD) (Ushi) (Spreads Joined).cbz", "Umineko When They Cry - Episode 1 - Legend of the Golden Witch")]
    [InlineData("Umineko When They Cry - Episode 8 - Twilight of the Golden Witch v01 (3-in-1 Edition) (2019) (Digital SD) (Ushi) (Spreads Joined).cbz", "Umineko When They Cry - Episode 8 - Twilight of the Golden Witch")]
    [InlineData("JoJo's Bizarre Adventure - Part 1 - Phantom Blood v01 (2014) (Digital) (BlackManta-Empire).cbz", "JoJo's Bizarre Adventure - Part 1 - Phantom Blood")]
    [InlineData("JoJo's Bizarre Adventure - Part 5 - Golden Wind v01 (2021) (Digital) (1r0n) (f2).cbz", "JoJo's Bizarre Adventure - Part 5 - Golden Wind")]
    [InlineData("Ascendance of a Bookworm - Part 01 v01 (2021) (Digital) (Ushi).cbz", "Ascendance of a Bookworm - Part 01")]
    [InlineData("Ascendance of a Bookworm - Part 02 v01 (2021) (Digital) (Ushi).cbz", "Ascendance of a Bookworm - Part 02")]
    [InlineData("Rose Guns Days - Season 1 v01 (2015) (Digital) (LuCaZ).cbz", "Rose Guns Days - Season 1")]
    [InlineData("Rose Guns Days - Season 2 v01 (2016) (Digital) (LuCaZ).cbz", "Rose Guns Days - Season 2")]
    [InlineData("Showa - A History of Japan v01 - 1926-1939 (2013) (Digital) (XRA-Empire).cbz", "Showa - A History of Japan")]
    [InlineData("Showa - A History of Japan v02 - 1939-1944 (2014) (Digital) (XRA-Empire).cbz", "Showa - A History of Japan")]
    [InlineData("Showa - A History of Japan v03 - 1944-1953 (2014) (Digital) (XRA-Empire).cbz", "Showa - A History of Japan")]
    [InlineData("Showa - A History of Japan v04 - 1953-1989 (2015) (Digital) (XRA-Empire).cbz", "Showa - A History of Japan")]
    [InlineData("Path of the Assassin v09 - Battle for Power Part 1 (2008) (Digital) (Lovag-Empire).cbz", "Path of the Assassin")]
    [InlineData("Path of the Assassin v10 - Battle for Power Part 2 (2008) (Digital) (Lovag-Empire).cbz", "Path of the Assassin")]
    [InlineData("Kaiju No. 8 v01 (2021) (Digital) (1r0n) (f).cbz", "Kaiju No. 8")]
    [InlineData("No. 5 v01 (2021) (Digital) (1r0n) (f2).cbz", "No. 5")]
    [InlineData("No. 6 v1 (2015) (Digital) (ripper).cbz", "No. 6")]
    // GH #1534: ripper tag "c1fi7" must not interfere with reading the series name either
    [InlineData("No. 6 v1 (2015) (Digital) (c1fi7).cbz", "No. 6")]
    [InlineData("Some Manga v01 (2015) (Digital) (Mr. Kimiko-c1fi7).cbz", "Some Manga")]
    public void ParseSeriesTest(string filename, string expected)
    {
        Assert.Equal(expected, Parser.ParseSeries(filename, LibraryType.Manga));
    }

    [Theory]
    [InlineData("Killing Bites Vol. 0001 Ch. 0001 - Galactica Scanlations (gb)", "1")]
    [InlineData("My Girlfriend Is Shobitch v01 - ch. 09 - pg. 008.png", "9")]
    [InlineData("Historys Strongest Disciple Kenichi_v11_c90-98.zip", "90-98")]
    [InlineData("B_Gata_H_Kei_v01[SlowManga&OverloadScans]", Parser.DefaultChapter)]
    [InlineData("BTOOOM! v01 (2013) (Digital) (Shadowcat-Empire)", Parser.DefaultChapter)]
    [InlineData("Gokukoku no Brynhildr - c001-008 (v01) [TrinityBAKumA]", "1-8")]
    [InlineData("Dance in the Vampire Bund v16-17 (Digital) (NiceDragon)", Parser.DefaultChapter)]
    [InlineData("c001", "1")]
    [InlineData("[Suihei Kiki]_Kasumi_Otoko_no_Ko_[Taruby]_v1.12.zip", Parser.DefaultChapter)]
    [InlineData("Adding volume 1 with File: Ana Satsujin Vol. 1 Ch. 5 - Manga Box (gb).cbz", "5")]
    [InlineData("Hinowa ga CRUSH! 018 (2019) (Digital) (LuCaZ).cbz", "18")]
    [InlineData("Cynthia The Mission - c000-006 (v06) [Desudesu&Brolen].zip", "0-6")]
    [InlineData("[WS]_Ichiban_Ushiro_no_Daimaou_v02_ch10.zip", "10")]
    [InlineData("Loose_Relation_Between_Wizard_and_Apprentice_c07[AN].zip", "7")]
    [InlineData("Tower Of God S01 014 (CBT) (digital).cbz", "14")]
    [InlineData("Tenjou_Tenge_c106[MT].zip", "106")]
    [InlineData("Tenjou_Tenge_v17_c100[MT].zip", "100")]
    [InlineData("Shimoneta - Manmaru Hen - c001-006 (v01) [Various].zip", "1-6")]
    [InlineData("Mujaki no Rakuen Vol12 ch76", "76")]
    [InlineData("Beelzebub_01_[Noodles].zip", "1")]
    [InlineData("Yumekui-Merry_DKThias_Chapter21.zip", "21")]
    [InlineData("Yumekui_Merry_v01_c01[Bakayarou-Kuu].rar", "1")]
    [InlineData("Yumekui-Merry_DKThias_Chapter11v2.zip", "11")]
    [InlineData("Yumekui-Merry DKThiasScanlations Chapter51v2", "51")]
    [InlineData("Yumekui-Merry_DKThiasScanlations&RenzokuseiScans_Chapter61", "61")]
    [InlineData("Goblin Slayer Side Story - Year One 017.5", "17.5")]
    [InlineData("Beelzebub_53[KSH].zip", "53")]
    [InlineData("Black Bullet - v4 c20.5 [batoto]", "20.5")]
    [InlineData("Itoshi no Karin - c001-006x1 (v01) [Renzokusei Scans]", "1-6")]
    [InlineData("APOSIMZ 040 (2020) (Digital) (danke-Empire).cbz", "40")]
    [InlineData("Kedouin Makoto - Corpse Party Musume, Chapter 12", "12")]
    [InlineData("Vol 1", Parser.DefaultChapter)]
    [InlineData("VanDread-v01-c001[MD].zip", "1")]
    [InlineData("Goblin Slayer Side Story - Year One 025.5", "25.5")]
    [InlineData("Kedouin Makoto - Corpse Party Musume, Chapter 01", "1")]
    [InlineData("To Love Ru v11 Uncensored (Ch.089-097+Omake)", "89-97")]
    [InlineData("To Love Ru v18 Uncensored (Ch.153-162.5)", "153-162.5")]
    [InlineData("[AN] Mahoutsukai to Deshi no Futekisetsu na Kankei Chp. 1", "1")]
    [InlineData("Beelzebub_Side_Story_02_RHS.zip", "2")]
    [InlineData("[PROzess]Kimi_ha_midara_na_Boku_no_Joou_-_Ch01", "1")]
    [InlineData("Fullmetal Alchemist chapters 101-108.cbz", "101-108")]
    [InlineData("Umineko no Naku Koro ni - Episode 3 - Banquet of the Golden Witch #02.cbz", "2")]
    [InlineData("To Love Ru v09 Uncensored (Ch.071-079).cbz", "71-79")]
    [InlineData("Corpse Party -The Anthology- Sachikos game of love Hysteric Birthday 2U Extra Chapter.rar", Parser.DefaultChapter)]
    [InlineData("Beelzebub_153b_RHS.zip", "153.5")]
    [InlineData("Beelzebub_150-153b_RHS.zip", "150-153.5")]
    [InlineData("Transferred to another world magical swordsman v1.1", Parser.DefaultChapter)]
    [InlineData("Kiss x Sis - Ch.15 - The Angst of a 15 Year Old Boy.cbz", "15")]
    [InlineData("Kiss x Sis - Ch.12 - 1 , 2 , 3P!.cbz", "12")]
    [InlineData("Umineko no Naku Koro ni - Episode 1 - Legend of the Golden Witch #1", "1")]
    [InlineData("Kiss x Sis - Ch.00 - Let's Start from 0.cbz", "0")]
    [InlineData("[Hidoi]_Amaenaideyo_MS_vol01_chp02.rar", "2")]
    [InlineData("Okusama wa Shougakusei c003 (v01) [bokuwaNEET]", "3")]
    [InlineData("Tomogui Kyoushitsu - Chapter 006 Game 005 - Fingernails On Right Hand (Part 002).cbz", "6")]
    [InlineData("Noblesse - Episode 406 (52 Pages).7z", "406")]
    [InlineData("X-Men v1 #201 (September 2007).cbz", "201")]
    [InlineData("Kodoja #001 (March 2016)", "1")]
    [InlineData("Noblesse - Episode 429 (74 Pages).7z", "429")]
    [InlineData("Boku No Kokoro No Yabai Yatsu - Chapter 054 I Prayed At The Shrine (V0).cbz", "54")]
    [InlineData("Ijousha No Ai - Vol.01 Chapter 029 8 Years Ago", "29")]
    [InlineData("Kedouin Makoto - Corpse Party Musume, Chapter 09.cbz", "9")]
    [InlineData("Hentai Ouji to Warawanai Neko. - Vol. 06 Ch. 034.5", "34.5")]
    [InlineData("Kimi no Koto ga Daidaidaidaidaisuki na 100-nin no Kanojo Chapter 1-10", "1-10")]
    [InlineData("Deku_&_Bakugo_-_Rising_v1_c1.1.cbz", "1.1")]
    [InlineData("Chapter 63 - The Promise Made for 520 Cenz.cbr", "63")]
    [InlineData("Harrison, Kim - The Good, The Bad, and the Undead - Hollows Vol 2.5.epub", Parser.DefaultChapter)]
    [InlineData("Kaiju No. 8 036 (2021) (Digital)", "36")]
    [InlineData("Samurai Jack Vol. 01 - The threads of Time", Parser.DefaultChapter)]
    [InlineData("【TFO汉化&Petit汉化】迷你偶像漫画第25话", "25")]
    [InlineData("자유록 13회#2", "13")]
    [InlineData("이세계에서 고아원을 열었지만, 어째서인지 아무도 독립하려 하지 않는다 38-1화 ", "38")]
    [InlineData("[ハレム]ナナとカオル ～高校生のSMごっこ～　第10話", "10")]
    [InlineData("Dance in the Vampire Bund {Special Edition} v03.5 (2019) (Digital) (KG Manga)", Parser.DefaultChapter)]
    [InlineData("Kebab Том 1 Глава 3", "3")]
    [InlineData("Манга Глава 2", "2")]
    [InlineData("Манга 2 Глава", "2")]
    [InlineData("Манга Том 1 2 Глава", "2")]
    [InlineData("Accel World Chapter 001 Volume 002", "1")]
    [InlineData("Bleach 001-003", "1-3")]
    [InlineData("Accel World Volume 2", Parser.DefaultChapter)]
    [InlineData("Historys Strongest Disciple Kenichi_v11_c90-98", "90-98")]
    [InlineData("Historys Strongest Disciple Kenichi c01-c04", "1-4")]
    [InlineData("Adabana c00-02", "0-2")]
    [InlineData("เด็กคนนี้ขอลาออกจากการเป็นเจ้าของปราสาท เล่ม 1 ตอนที่ 3", "3")]
    [InlineData("Max Level Returner ตอนที่ 5", "5")]
    [InlineData("หนึ่งความคิด นิจนิรันดร์ บทที่ 112", "112")]
    [InlineData("Monster #8 Ch. 001", "1")]
    [InlineData("Monster Ch. 001 [MangaPlus] [Digital] [amit34521]", "1")]
    [InlineData("Naruto v2.5", Parser.DefaultChapter)]
    [InlineData("조선왕조실톡 106화", "106")]
    [InlineData("나루토 1.5권", Parser.DefaultChapter)]
    // A bare year in the title before an explicit Volume/Tome marker should not be mistaken for a chapter number
    [InlineData("Blade Runner 2019 - Volume 1.pdf", Parser.DefaultChapter)]
    [InlineData("Blade Runner 2019 - Volume 1", Parser.DefaultChapter)]
    [InlineData("Blade_Runner_2019_-_Volume_1", Parser.DefaultChapter)]
    [InlineData("Blade Runner 2019 - Vol. 1.pdf", Parser.DefaultChapter)]
    [InlineData("Blade Runner 2019 - Tome 1.cbz", Parser.DefaultChapter)]
    [InlineData("Cyberpunk 2077 - Volume 2.cbz", Parser.DefaultChapter)]
    // A bare number immediately before an abbreviated volume marker is part of the series title
    // ("Foo 50", like "Golgo 13" or "Kaiju No. 8"), not a chapter number.
    [InlineData("Foo 50 v1.cbz", Parser.DefaultChapter)]
    // A bare year in the title before an explicit Chapter marker should not be mistaken for the chapter number itself
    [InlineData("Blade Runner 2019 - Ch. 1.pdf", "1")]
    [InlineData("Blade Runner 2019 - Chapter 1.pdf", "1")]
    [InlineData("Blade Runner 2019 - Ch 1.pdf", "1")]
    // GH #1534: a number embedded in the series title of a volume-only release should not be
    // mistaken for a chapter number just because a Volume marker exists elsewhere in the filename.
    [InlineData("ACCA - 13-Territory Inspection Department v01 (2017) (Digital) (Uasaha).cbz", Parser.DefaultChapter)]
    [InlineData("ACCA - 13-Territory Inspection Department P.S. v01 (2020) (Digital) (LuCaZ).cbz", Parser.DefaultChapter)]
    [InlineData("Brave 10 v01 (2013) (Digital) (Lovag-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Black Panther and Sweet 16 v01 (2017) (Digital) (danke-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Boys Over Flowers Season 2 v01 (2017) (Digital) (ripper).cbz", Parser.DefaultChapter)]
    [InlineData("Chillin' in Another World with Level 2 Super Cheat Powers v01 (2021) (Digital) (danke-Empire + nao).cbz", Parser.DefaultChapter)]
    [InlineData("Cyborg 009 v01 (2003) (Digital) (BlurPixel-Empire).cbr", Parser.DefaultChapter)]
    [InlineData("Dementia 21 v01 (2018) (digital) (tunafan).cbr", Parser.DefaultChapter)]
    [InlineData("Golgo 13 v01 - Supergun (2006) (Digital) (danke-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("GTO - 14 Days in Shonan v01 (2022) (Digital) (danke-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Level 1 Demon Lord & One Room Hero v01 (2021) (Digital) (danke-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("My Unique Skill Makes Me OP Even at Level 1 v01 (2021) (Digital) (danke-Empire) (F).cbz", Parser.DefaultChapter)]
    [InlineData("Otherworldly Munchkin - Let's Speedrun the Dungeon with Only 1 HP! v01 (2020) (Digital) (danke-Empire) (F).cbz", Parser.DefaultChapter)]
    [InlineData("Rosario+Vampire Season 2 v01 (2010) (Digital) (LostNerevarine-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Samurai 8 v01 (2020) (Digital) (danke-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Samurai 8 - The Tale of Hachimaru v01 (2020) (Digital) (danke-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Saving 80,000 Gold in Another World for my Retirement v01 (2019) (Digital) (danke-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Sekirei v19 - 365 Days Without Her (2018) (Digital) (RedRain).cbz", Parser.DefaultChapter)]
    [InlineData("Sex Ed 120% v01 (2021) (Digital) (danke-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Higurashi When They Cry - Arc 1 - Abducted by Demons Arc v01 (2008) (Digital) (LuCaZ).cbz", Parser.DefaultChapter)]
    [InlineData("Umineko When They Cry - Episode 1 - Legend of the Golden Witch v01 (2-in-1 Edition) (2012) (Digital SD) (Ushi) (Spreads Joined).cbz", Parser.DefaultChapter)]
    [InlineData("Umineko When They Cry - Episode 8 - Twilight of the Golden Witch v01 (3-in-1 Edition) (2019) (Digital SD) (Ushi) (Spreads Joined).cbz", Parser.DefaultChapter)]
    [InlineData("JoJo's Bizarre Adventure - Part 1 - Phantom Blood v01 (2014) (Digital) (BlackManta-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("JoJo's Bizarre Adventure - Part 5 - Golden Wind v01 (2021) (Digital) (1r0n) (f2).cbz", Parser.DefaultChapter)]
    [InlineData("Ascendance of a Bookworm - Part 01 v01 (2021) (Digital) (Ushi).cbz", Parser.DefaultChapter)]
    [InlineData("Ascendance of a Bookworm - Part 02 v01 (2021) (Digital) (Ushi).cbz", Parser.DefaultChapter)]
    [InlineData("Rose Guns Days - Season 1 v01 (2015) (Digital) (LuCaZ).cbz", Parser.DefaultChapter)]
    [InlineData("Rose Guns Days - Season 2 v01 (2016) (Digital) (LuCaZ).cbz", Parser.DefaultChapter)]
    [InlineData("Showa - A History of Japan v01 - 1926-1939 (2013) (Digital) (XRA-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Showa - A History of Japan v02 - 1939-1944 (2014) (Digital) (XRA-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Showa - A History of Japan v03 - 1944-1953 (2014) (Digital) (XRA-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Showa - A History of Japan v04 - 1953-1989 (2015) (Digital) (XRA-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Path of the Assassin v09 - Battle for Power Part 1 (2008) (Digital) (Lovag-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Path of the Assassin v10 - Battle for Power Part 2 (2008) (Digital) (Lovag-Empire).cbz", Parser.DefaultChapter)]
    [InlineData("Kaiju No. 8 v01 (2021) (Digital) (1r0n) (f).cbz", Parser.DefaultChapter)]
    [InlineData("No. 5 v01 (2021) (Digital) (1r0n) (f2).cbz", Parser.DefaultChapter)]
    [InlineData("No. 6 v1 (2015) (Digital) (ripper).cbz", Parser.DefaultChapter)]
    // GH #1534: ripper tag "c1fi7" (a scanlation group's name, not a chapter marker) gets misread as "c1"
    [InlineData("No. 6 v1 (2015) (Digital) (c1fi7).cbz", Parser.DefaultChapter)]
    [InlineData("Some Manga v01 (2015) (Digital) (Mr. Kimiko-c1fi7).cbz", Parser.DefaultChapter)]
    // "31" is part of the series title ("The Long Summer of August 31"), not a chapter number.
    [InlineData("The Long Summer of August 31 Vol. 1.cbz", Parser.DefaultChapter)]
    [InlineData("BTOOOM! v03 (2013) (Digital) (c1fi7) (ED).cbz", Parser.DefaultChapter)]
    [InlineData("Series - c079x1 (2025) - Creator's Note.cbz", "79")]
    public void ParseChaptersTest(string filename, string expected)
    {
        Assert.Equal(expected, Parser.ParseChapter(filename, LibraryType.Manga));
    }

    /// <summary>
    /// Handles edge case testing around duplicate numbers in the filename
    /// </summary>
    [Theory]
    [InlineData("Manga Title - Ch.1 - The 22 beers", "1")]
    public void ParseExtraNumberChaptersTest(string filename, string expected)
    {
        Assert.Equal(expected, Parser.ParseChapter(filename, LibraryType.Manga));
    }

    [Theory]
    [InlineData("Manga Title - Ch.1 Part.A - Ch.2 Omake", "1")]
    [InlineData("Another Series - Chapter 10 Something - Chapter 15 Extra", "10")]
    [InlineData("Test_Ch_3_Content_Ch_7_Bonus", "3")]
    [InlineData("One Piece - Ch 5 Part 1 - Chapter 10 Omakes", "5")]
    [InlineData("Attack on Titan - Chapter 20 Content - Ch 25 Special", "20")]
    [InlineData("Naruto - Ch. 1 Story - Ch. 5 Preview", "1")]
    [InlineData("My Hero Academia - Chapter 15 - Chapter 20 Extras", "15")]
    [InlineData("Series Name - c2 Content - c5 Bonus", "2")]
    [InlineData("Test Series - c1 Part1 - Chapter 3 Extra", "1")]
    [InlineData("Another Test - Chapter 7 - c10 Omake", "7")]
    [InlineData("Series - Ch 1 - Not Ch but Chaos", "1")]
    [InlineData("Chapter Wars - Ch 1 vs Ch 2", "1")]
    [InlineData("Ch 3 - The Chapter Chronicles - Ch 5", "3")]
    public void ParseDuplicateChapterTest(string filename, string expected)
    {
        Assert.Equal(expected, Parser.ParseChapter(filename, LibraryType.Manga));
    }


    [Theory]
    [InlineData("Tenjou Tenge Omnibus", "Omnibus")]
    [InlineData("Tenjou Tenge {Full Contact Edition}", "")]
    [InlineData("Tenjo Tenge {Full Contact Edition} v01 (2011) (Digital) (ASTC).cbz", "")]
    [InlineData("Wotakoi - Love is Hard for Otaku Omnibus v01 (2018) (Digital) (danke-Empire)", "Omnibus")]
    [InlineData("To Love Ru v01 Uncensored (Ch.001-007)", "Uncensored")]
    [InlineData("Chobits Omnibus Edition v01 [Dark Horse]", "Omnibus Edition")]
    [InlineData("Chobits_Omnibus_Edition_v01_[Dark_Horse]", "Omnibus Edition")]
    [InlineData("[dmntsf.net] One Piece - Digital Colored Comics Vol. 20 Ch. 177 - 30 Million vs 81 Million.cbz", "")]
    [InlineData("AKIRA - c003 (v01) [Full Color] [Darkhorse].cbz", "")]
    [InlineData("Love Hina Omnibus v05 (2015) (Digital-HD) (Asgard-Empire).cbz", "Omnibus")]
    public void ParseEditionTest(string input, string expected)
    {
        Assert.Equal(expected, Parser.ParseEdition(input));
    }

    [Theory]
    [InlineData("Beelzebub Special OneShot - Minna no Kochikame x Beelzebub (2016) [Mangastream].cbz", false)]
    [InlineData("Beelzebub_Omake_June_2012_RHS", false)]
    [InlineData("Beelzebub_Side_Story_02_RHS.zip", false)]
    [InlineData("Darker than Black Shikkoku no Hana Special [Simple Scans].zip", false)]
    [InlineData("Darker than Black Shikkoku no Hana Fanbook Extra [Simple Scans].zip", false)]
    [InlineData("Corpse Party -The Anthology- Sachikos game of love Hysteric Birthday 2U Extra Chapter", false)]
    [InlineData("Ani-Hina Art Collection.cbz", false)]
    [InlineData("Gifting The Wonderful World With Blessings! - 3 Side Stories [yuNS][Unknown]", false)]
    [InlineData("A Town Where You Live - Bonus Chapter.zip", false)]
    [InlineData("Yuki Merry - 4-Komga Anthology", false)]
    [InlineData("Beastars - SP01", true)]
    [InlineData("Beastars SP01", true)]
    [InlineData("The League of Extraordinary Gentlemen", false)]
    [InlineData("The League of Extra-ordinary Gentlemen", false)]
    [InlineData("Dr. Ramune - Mysterious Disease Specialist v01 (2020) (Digital) (danke-Empire)", false)]
    [InlineData("Hajime no Ippo - Artbook", false)]
    public void IsMangaSpecialTest(string input, bool expected)
    {
        Assert.Equal(expected, Parser.IsSpecial(input, LibraryType.Manga));
    }

    [Theory]
    [InlineData("image.png", MangaFormat.Image)]
    [InlineData("image.cbz", MangaFormat.Archive)]
    [InlineData("image.txt", MangaFormat.Unknown)]
    public void ParseFormatTest(string inputFile, MangaFormat expected)
    {
        Assert.Equal(expected, Parser.ParseFormat(inputFile));
    }


}
