name: Build UI

on:
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  build:
    name: Build UI
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          fetch-depth: 1

      - name: NodeJS to Compile WebUI
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
      - run: |
          cd UI/Web || exit
          echo 'Installing web dependencies'
          npm ci

          echo 'Building UI'
          npm run prod
