name: Build and Test PR

on:
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  build:
    name: Build and Test PR
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
            fetch-depth: 1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
            dotnet-version: 10.0.x

      - name: Install Swashbuckle CLI
        shell: powershell
        run: dotnet tool install -g Swashbuckle.AspNetCore.Cli

      - name: Install dependencies
        run: dotnet restore

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: csproj
          path: Kavita.Common/Kavita.Common.csproj

      - name: Test
        run: dotnet test --no-restore --verbosity normal --filter "Category!=Integration"
