name: Build UI

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Build UI
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: NodeJS to Compile WebUI
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: UI/Web/package-lock.json
      - run: |
          cd UI/Web || exit
          echo 'Installing web dependencies'
          npm ci

          echo 'Building UI'
          npm run prod
