name: CI to Docker Hub

on:
  push:
    branches:
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Check Out WebUI
        uses: actions/checkout@v2
        with:
          repository: Kareadita/Kavita-webui
          ref: feature/sentry-release
          path: Kavita-webui/

      - name: NodeJS to Compile WebUI
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - run: |
          cd Kavita-webui/ || exit
          npm install
          npm run prod
          mv dist/ ../wwwroot
          cd ../ || exit

      - name: Compile dotnet app
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: |
          chmod +x action-build.sh
          ./action-build.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: kizaing
          password: 5cff908a-7ef6-47c9-ad97-160df5575f07

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: kizaing/kavita:nightly-test

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
