name: Release Workflow

on:
  push:
    branches: ["develop", "canary"]

permissions:
  contents: write
  issues: write
  pull-requests: read
  packages: write

jobs:
  run-release-tool:
    if: github.repository == 'Kareadita/Kavita'
    uses: Kareadita/GitHubActions/.github/workflows/release-tools.base.yml@main
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    with:
      config-path: release.yaml
      dockerhub-username: "jvmilazz0"
      uses-docker: true
