name: Release Workflow

on:
  pull_request_target:
    types: [closed]
    branches: ["develop", "canary"]
  workflow_dispatch:

jobs:
  run-release-tool:
    if: github.repository == 'Kareadita/Kavita' && github.event.pull_request.merged == true
    uses: Kareadita/GitHubActions/.github/workflows/release-tools.base.yml@main
    secrets: inherit
    with:
      config-path: release.yaml
      dockerhub-username: "jvmilazz0"
