name: Version Bump
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version to update package.json"
        required: true
        # No default
      branch:
        description: "tells us which branch to merge the bump into"
        required: true
        # No default

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: version-bump-${{ github.event.inputs.version }}
          fetch-depth: 0

      - name: Create local changes for reference
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit --allow-empty -m "Trigger Build"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Bump versions
        uses: SiqiLu/dotnet-bump-version@master
        with:
          version_files: /Kavita.Common/Kavita.Common.csproj
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge bump -> pr
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: version-bump-${{ github.event.inputs.version }}
          target_branch: ${{ github.event.inputs.branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}