name: Version Bump
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version to update package.json"
        required: true
        # No default
      branch:
        description: "tells us which branch to merge the bump into"
        required: true
        # No default

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: version-bump-${{ github.event.inputs.version }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Bump versions
        uses: SiqiLu/dotnet-bump-version@master
        with:
          version_files: Kavita.Common/Kavita.Common.csproj
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge bump -> pr
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: version-bump-${{ github.event.inputs.version }}
          target_branch: ${{ github.event.inputs.branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}